### ISSUE TITLE
Add a link to Cincy WWCode meetup page 

### ISSUE THREAD

**Issue by sandiritter** [WomenWhoCodeCincy/WomenWhoCodeCincy.github.io#19]

**Comment by BayLadyCoder** [comment]
Can you provide the link, please?

**Comment by sandiritter** [comment]
https://www.facebook.com/groups/wwcodecincinnati

**Comment by sierraobryan** [comment]
Hey @BayLadyCoder it looks like someone already added the FaceBook link- this is our fault! We're trying to keep up and nothing gets done twice. Sorry!! Can you add our meet up link instead? It should be the same exact same step! I'll update this issue to reflect the new task and make sure no one else works on it! Thank you for your flexibility 
The link is https://www.meetup.com/Women-Who-Code-Cincinnati/ but it should be part of the response from the network call to the back end (it will be an attribute on the Links object in the contact information object)!

**Comment by BayLadyCoder** [comment]
@sierraobryan Thanks for the info. I just added the meetup link to the database. Once it's merged to the database, then I can work on this  issue.

**Comment by sierraobryan** [comment]
@BayLadyCoder merged in!
