### ISSUE TITLE
Make the header responsive

### ISSUE THREAD

**Issue by alexxmitchell** [WomenWhoCodeCincy/WomenWhoCodeCincy.github.io#9]

**Comment by jeremylgrice** [comment]
Mind if I work on this one? Quick question though, and I apologize if I overlooked it, but are there designs or a style guide with how everyone wants this to look?

**Comment by sierraobryan** [comment]
@alexxmitchell @sandiritter do you have a guide you're following for @jeremylgrice to follow?

@jeremylgrice in general, we're just following best practices, keeping to the WWCode colors, and leaving some creativity to the developer and continue to iterate (and make new issues) as we need to to build a final product! Thanks for your interest in contributing!

**Comment by jeremylgrice** [comment]
@sierraobryan You're welcome, and thank you for pointing me to this. I appreciate everything! Is there a Slack channel? I'd love to help where I can!

**Comment by sierraobryan** [comment]
@jeremylgrice Yes! Please [join](https://join.slack.com/t/wwcodecincinnati/shared_invite/zt-iihz87hd-1SroM2tLT7cmuMTjRvazzg) the Hacktoberfest channel

**Comment by jeremylgrice** [comment]
I opened the PR up for the header, but it won't let me assign anyone as a reviewer or edit anything on the right hand side. Any thoughts?

**Comment by alexxmitchell** [comment]
No, there isn't a style guide 🙈 . @jeremylgrice thanks for your contribution!
